### ISSUE TITLE
Cannot read properties of undefined (reading 'options')   

### ISSUE THREAD

**Issue by nightlyworker** [ijkml/nuxt-umami#117]
Hi there,
Thank you for you module. The V3 looks real gold. I just followed your guide (https://ijkml.dev/posts/nuxt-umami-v3?ref=https://umami.nuxt.dev)  and I get error bellow.

Please, Any chance you can give some hint (or fix) how to resolve it ?

Thank you very much

```
    "nuxt-umami": "^3.0.1",
```

```
$ nuxt dev
Nuxt 3.13.1 with Nitro 2.9.7                                                                                             11:19:01 AM

 ERROR  Cannot read properties of undefined (reading 'options')                                                          11:19:01 AM

  at Object.normalizedModule (node_modules/@nuxt/kit/dist/index.mjs:2116:12)
  at node_modules/nuxt-umami/dist/module.cjs:2:53
  at async resolveConfig (/home/martin/node_modules/c12/dist/index.mjs:333:18)
  at async extendConfig (/home/martin/node_modules/c12/dist/index.mjs:241:21)
  at async loadConfig (/home/martin/node_modules/c12/dist/index.mjs:176:5)
  at async loadNuxtConfig (/home/martin/node_modules/@nuxt/kit/dist/index.mjs:2516:18)
  at async Object.run (node_modules/nuxi/dist/chunks/dev.mjs:171:25)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1648:16)
  at async runCommand$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1639:11)
  at async runMain$1 (node_modules/nuxi/dist/shared/nuxi.fefc5017.mjs:1777:7) 

```

**Comment by ijkml** [comment]
Oh, sorry about that, and thanks for pointing it out. I'll add it to the upgrade guide.

Thank you.
