### ISSUE TITLE
3.0.2 crashes nuxi, reverting to 2.6.7 fixes it.

### ISSUE THREAD

**Issue by octo-kumo** [ijkml/nuxt-umami#119]
After installing 3.0.2 of `nuxt-umami`, `nuxi` will not start, `nuxi dev`, `nuxi cleanup` etc will all fail.

```
 ERROR  Cannot read properties of undefined (reading 'options')                                                                           1:05:01 am  

  at Object.normalizedModule (/node_modules/.pnpm/@nuxt+kit@3.13.2_magicast@0.3.5_rollup@4.23.0_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2116:12)
  at node_modules\.pnpm\nuxt-umami@3.0.2_magicast@0.3.5_rollup@4.23.0_webpack-sources@3.2.3\node_modules\nuxt-umami\dist\module.cjs:2:53
  at async resolveConfig (/node_modules/.pnpm/c12@1.11.2_magicast@0.3.5/node_modules/c12/dist/shared/c12.cab0c9da.mjs:348:18)
  at async extendConfig (/node_modules/.pnpm/c12@1.11.2_magicast@0.3.5/node_modules/c12/dist/shared/c12.cab0c9da.mjs:255:21)
  at async loadConfig (/node_modules/.pnpm/c12@1.11.2_magicast@0.3.5/node_modules/c12/dist/shared/c12.cab0c9da.mjs:187:5)
  at async loadNuxtConfig (/node_modules/.pnpm/@nuxt+kit@3.13.2_magicast@0.3.5_rollup@4.23.0_webpack-sources@3.2.3/node_modules/@nuxt/kit/dist/index.mjs:2597:18)
  at async Object.run (/node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/chunks/dev.mjs:171:25) 
  at async runCommand$1 (/node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1648:16)
  at async runCommand$1 (/node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1639:11)
  at async runMain$1 (/node_modules/.pnpm/nuxi@3.13.2/node_modules/nuxi/dist/shared/nuxi.b8b195e1.mjs:1777:7)

 ERROR  Cannot read properties of undefined (reading 'options')
```

Reverting back to 2.6.7 fixes the issue.

nuxt version: `3.13.2`
nuxi version `3.14.0`

**Comment by octo-kumo** [comment]
sorry did not read migrate notes
