### ISSUE TITLE
`defineNuxtConfig` not defined

### ISSUE THREAD

**Issue by cpreston321** [ijkml/nuxt-umami#54]
```bash
- Operating System: `Darwin`
- Node Version:     `v18.15.0`
- Nuxt Version:     `3.4.1`
- Nitro Version:    `2.3.3`
- Package Manager:  `pnpm@8.1.1`
- Builder:          `vite`
- User Config:      `css`, `runtimeConfig`, `app`, `extends`, `appConfig`, `modules`, `turnstile`, `colorMode`, `motion`, `unocss`, `image`
- Runtime Modules:  `nuxt-icon@0.3.3`, `@nuxtjs/turnstile@0.2.0`, `@unocss/nuxt@0.51.4`, `@nuxt/content@2.5.2`, `@nuxt/image-edge@1.0.0-28008586.381b906`, `@vueuse/nuxt@9.13.0`, `@vueuse/motion/nuxt@2.0.0-beta.27`, `@formkit/nuxt@0.16.4`, `nuxt-umami@2.2.0`, `@nuxtjs/color-mode@3.2.0`, `@nuxthq/studio@0.10.1`
- Build Modules:    `-`
```

```bash
Cannot start nuxt:  defineNuxtConfig is not defined                                                                    3:13:44 PM

  at node_modules/.pnpm/nuxt-umami@2.2.0/node_modules/nuxt-umami/nuxt.config.ts:1:178
  at jiti (node_modules/.pnpm/jiti@1.18.2/node_modules/jiti/dist/jiti.js:1:245784)
  at requireModule (node_modules/.pnpm/@nuxt+kit@3.4.1/node_modules/@nuxt/kit/dist/index.mjs:286:26)
  at normalizeModule (node_modules/.pnpm/@nuxt+kit@3.4.1/node_modules/@nuxt/kit/dist/index.mjs:472:77)
  at installModule (node_modules/.pnpm/@nuxt+kit@3.4.1/node_modules/@nuxt/kit/dist/index.mjs:451:47)
  at initNuxt (node_modules/.pnpm/nuxt@3.4.1_@types+node@18.15.11_eslint@8.38.0_typescript@5.0.4/node_modules/nuxt/dist/index.mjs:2616:13)
  at async load (node_modules/.pnpm/nuxi@3.4.1/node_modules/nuxi/dist/chunks/dev.mjs:6824:9)
  at async Object.invoke (node_modules/.pnpm/nuxi@3.4.1/node_modules/nuxi/dist/chunks/dev.mjs:6874:5)
  at async _main (node_modules/.pnpm/nuxi@3.4.1/node_modules/nuxi/dist/cli.mjs:47:20)
```

**Comment by ijkml** [comment]
Hey @cpreston321, I can't seem to reproduce the error.
Let's try this Stackblitz repro: https://stackblitz.com/edit/nuxt-umami-next.

**Comment by cpreston321** [comment]
Hey @ijkml! Must of overlooked the migration and forgot to remove it from `modules: []` once I did that it fixed it! Sorry for the inconvenience. 

Thanks,
CP

**Comment by ijkml** [comment]
Ah, okay, no problem at all.
