### ISSUE TITLE
defineNuxtConfig is not defined

### ISSUE THREAD

**Issue by mwinter80** [ijkml/nuxt-umami#62]
I am getting this error. I guess I am confused why there is a nuxt config file in the project. Please advise and thanks in advance!

```
[12:47:06 PM]  ERROR  Error while requiring module nuxt-umami: ReferenceError: defineNuxtConfig is not defined


[12:47:06 PM]  ERROR  Cannot restart nuxt:  defineNuxtConfig is not defined

  at node_modules/nuxt-umami/nuxt.config.ts:1:178
  at jiti (node_modules/jiti/dist/jiti.js:1:245784)
  at requireModule (node_modules/@nuxt/kit/dist/index.mjs:2241:26)
  at normalizeModule (node_modules/@nuxt/kit/dist/index.mjs:2433:90)
  at async installModule (node_modules/@nuxt/kit/dist/index.mjs:2406:41)
  at async initNuxt (node_modules/nuxt/dist/index.mjs:2928:7)
  at async load (node_modules/nuxi/dist/chunks/dev.mjs:204:9)
  at async _applyPromised (node_modules/nuxi/dist/chunks/dev.mjs:96:10)
```

**Comment by ijkml** [comment]
Hi @mwinter80, how did you register it? I'm guessing you added it to `modules: []`, check https://github.com/ijkml/nuxt-umami#step-1-install-and-add-to-nuxt

**Comment by mwinter80** [comment]
yes. I registered it in nodules:

export default defineNuxtConfig({
  modules: ['@nuxtjs/tailwindcss', '@nuxt/image', 'nuxt-icon', '@pinia/nuxt', 'nuxt-headlessui']
})

**Comment by mwinter80** [comment]
Now I am confused. Are you suggesting I use the v1 branch? Thanks and sorry for the trouble!

**Comment by ijkml** [comment]
Sorry for the confusion. I need some info to sort this out.

What version of the Nuxt Umami do you have installed (or want to use)? v1 and v2 are quite different, and it depends on the version of Nuxt you're using.

**Comment by mwinter80** [comment]
I am using Nuxt3 and was intending to use V2

**Comment by ijkml** [comment]
Great. That simplifies things. After installing, don't add it to modules, add this to `nuxt.config`

```ts
extends: ['nuxt-umami']
```

**Comment by mwinter80** [comment]
Yeah. that is super clear. I completely glossed over that it was "extends" not "modules". Was habitual. Sorry!

**Comment by ijkml** [comment]
Hey, no problem at all!
